spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: escape
    druid:
      maxWait: 30000
      initialSize: 10
      maxActive: 5000
      query-timeout: 60
      validation-query: select 1 from dual
      use-global-data-source-stat: true
  jpa:
    hibernate:
      #ddl-auto: create-drop   #清除数据库建表
      #ddl-auto: create        #不清除数据库建表
      ddl-auto: update         #保留数据库以及表更新数据库
      #ddl-auto: validate      #运行程序会校验数据与数据库的字段类型是否相同，不同会报错
    show-sql: true
server:
  port: 8884
